### ISSUE TITLE
The fatal flaw

### ISSUE THREAD

**Issue by oravecz** [TomFrost/Vers#11]
Performing just-in-time updates to the data model solves some use cases, but punts on others. How does one query against a data store with several different versions of the underlying data model?

**Comment by larssn** [comment]
@oravecz Did you ever find a solution for that question?

**Comment by oravecz** [comment]
Honestly, I don’t even recall the context of my question now. :)

**Comment by TomFrost** [comment]
FWIW-- the primary use case here is for a key/value store or API endpoint, where complex queries/searches are either unnecessary or are handled externally. If you're working with an SQL, ElasticSearch, or Mongo, Vers' usefulness is in allowing you to avoid downtime during long rollouts, but not for long-term use. If you're running anything Dynamo-based, Redis, or need to version APIs, Vers might have a long-term home in your stack. If you're finding yourself writing if-statements to assess the version of your data and then changing how you interact with it, this might be your answer!

I'm going to go ahead and close since this should clear up the use case issue, but please don't hesitate to continue the discussion if you're looking for implementation advice!
